version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:6.0
    container_name: webdy-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Backend Service
  backend:
    build: ./backend
    container_name: webdy-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/webdy
      - JWT_SECRET=WebdyPremiumSuperSecretAgencyToken2026!
      - ADMIN_EMAIL=admin@webdy.com
      - ADMIN_PASSWORD=AdminWebdy2026!
    depends_on:
      - mongodb
    volumes:
      - backend_fallback_data:/app/data

  # Frontend Service (Nginx Web Server + API Proxy)
  frontend:
    build: ./frontend
    container_name: webdy-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
  backend_fallback_data:
